-- Seed Ethiopian foods (run after schema.sql)
INSERT INTO ethiopian_foods (name_en, name_am, calories_per_serving, protein_g, carbs_g, fat_g, serving_description, is_fasting_friendly, category, image_url) VALUES
('Injera', 'እንጀራ', 205, 5, 42, 1, '1 large piece (30cm)', true, 'lunch', '/foods/injera.jpg'),
('Tibs', 'ጥብስ', 380, 28, 8, 26, '150g with vegetables', false, 'lunch', '/foods/tibs.jpg'),
('Shiro', 'ሽሮ', 220, 12, 28, 8, '1 cup', true, 'lunch', '/foods/shiro.jpg'),
('Misir Wot', 'ምስር ወጥ', 180, 10, 24, 5, '1 cup', true, 'lunch', '/foods/misir.jpg'),
('Kinche', 'ቅንጨ', 250, 8, 45, 4, '1 bowl', true, 'breakfast', '/foods/kinche.jpg'),
('Ful', 'ፉል', 320, 14, 45, 8, '1 bowl with bread', true, 'breakfast', '/foods/ful.jpg'),
('Kategna', 'ካተኛ', 280, 6, 38, 12, '2 pieces injera', true, 'snack', '/foods/kategna.jpg'),
('Firfir', 'ፍርፍር', 350, 12, 42, 14, '1 plate shredded injera', false, 'breakfast', '/foods/firfir.jpg'),
('Gored Gored', 'ጎረድ ጎረድ', 420, 32, 4, 30, '150g raw beef cubes', false, 'lunch', '/foods/gored.jpg'),
('Doro Wot', 'ዶሮ ወጥ', 480, 35, 18, 28, '1 leg piece + sauce', false, 'lunch', '/foods/doro.jpg'),
('Ayib', 'አይብ', 120, 8, 4, 9, '100g cottage cheese', false, 'snack', '/foods/ayib.jpg'),
('Teff Porridge', 'ጤፍ ሾርባ', 200, 6, 38, 3, '1 bowl', true, 'breakfast', '/foods/teff.jpg'),
('Sambusa', 'ሳምቡሳ', 180, 5, 22, 8, '2 pieces', true, 'snack', '/foods/sambusa.jpg'),
('Chechebsa', 'ጨጨብሳ', 400, 10, 55, 16, '1 plate', false, 'breakfast', '/foods/chechebsa.jpg'),
('Genfo', 'ገንፎ', 350, 8, 60, 8, '1 bowl with butter', false, 'breakfast', '/foods/genfo.jpg'),
('Enkulal Firfir', 'እንቁላል ፍርፍር', 380, 16, 40, 16, '1 plate with egg', false, 'breakfast', '/foods/enkulal.jpg'),
('Dulet', 'ዱለት', 450, 30, 6, 34, '150g organ meat mix', false, 'lunch', '/foods/dulet.jpg'),
('Derek Tibs', 'ደረቅ ጥብስ', 360, 26, 10, 24, '150g dry-fried meat', false, 'lunch', '/foods/derek.jpg'),
('Yetsom Beyaynetu', 'የጾም በያይነቱ', 420, 14, 65, 12, 'Fasting platter with 5 dishes', true, 'lunch', '/foods/beyaynetu.jpg'),
('Gomen', 'ጎመን', 120, 4, 12, 6, '1 cup collard greens', true, 'lunch', '/foods/gomen.jpg'),
('Atkilt', 'አትክልት', 150, 3, 28, 4, '1 cup mixed vegetables', true, 'lunch', '/foods/atkilt.jpg'),
('Beyaynetu', 'በያይነቱ', 550, 22, 70, 18, 'Combination platter', false, 'lunch', '/foods/beyaynetu-meat.jpg'),
('Kitfo', 'ክትፎ', 400, 30, 2, 30, '150g minced raw beef', false, 'lunch', '/foods/kitfo.jpg'),
('Bula', 'ቡላ', 180, 4, 35, 3, '1 bowl porridge', true, 'breakfast', '/foods/bula.jpg'),
('Chornake', 'ጮርናቄ', 300, 8, 48, 8, '1 plate', true, 'breakfast', '/foods/chornake.jpg'),
('Dabo Kolo', 'ዳቦ ቆሎ', 160, 4, 28, 4, '1 cup snack mix', true, 'snack', '/foods/dabo.jpg'),
('Telba Fitfit', 'ተልባ ፍትፍት', 290, 8, 38, 12, '1 bowl flaxseed dish', true, 'breakfast', '/foods/telba.jpg'),
('Azifa', 'አዚፋ', 160, 8, 18, 6, '1 cup green lentil salad', true, 'lunch', '/foods/azifa.jpg'),
('Fosolia', 'ፎሶሊያ', 140, 6, 20, 4, '1 cup green beans', true, 'lunch', '/foods/fosolia.jpg'),
('Bozena Shiro', 'ቦዘና ሽሮ', 260, 14, 30, 10, '1 cup with meat', false, 'lunch', '/foods/bozena.jpg')
ON CONFLICT DO NOTHING;
